// 🐸 Froggo puns collection
export const PUNS = [
    "You're toad-ally crushing it! 💚",
    "Hop to it — you've got this! 🐸",
    "You're one in a frogillion! ✨",
    "Warts and all, you're amazing! 💛",
    "You've really leaped to a new level today! 🌟",
    "Don't worry, be hoppy! 🌈",
    "You're ribbiting good company! 💚",
    "Time flies when frogs are having fun! ⏰",
    "You're such an ex-TOAD-inary person! 🎉",
    "Feeling ponds of joy just thinking of you! 🌿",
    "You make every lily pad brighter! 🌸",
    "You're the leap I needed today! 💫",
    "Keep going — you're un-FROG-gettable! 💖",
    "Today's forecast: 100% chance of hoppiness! ☀️",
    "You should be proud — that's a massive leap! 🦘",
    "Toad you so — you're incredible! 😄",
    "The pond wouldn't be the same without you! 🍃",
    "You're a fungi... wait no, a fun-FROG! 🍄",
    "Every big journey starts with a single hop! 🌒",
    "You're green with awesomeness! 💚",
    "Ribbit ribbit — that's frog for 'you're great'! 🐸",
    "Be-leafy in yourself, the pond is yours! 🌿",
    "You tadpoled through that like a champ! 🏆",
    "Like a lily pad in the wind — you're resilient! 💧",
    "Your vibes are im-pond-ibly good! ✨",
    "Toad-ays the day you shine! 🌟",
    "The whole pond is rooting for you! 🐢",
    "Croak croak — that's the sound of success! 🎵",
    "You're so cool, even dragonflies envy you! 🌀",
    "Leap into the day — you've totally got this! 🌅",
];

export const getRandomPun = () => PUNS[Math.floor(Math.random() * PUNS.length)];
